## IMPLEMENTATION OF CVAE

---



# IMPORT OF LIBRARIES

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#importing libraries
# for making dataframe and basic processing actions
import pandas as pd 
#importing tensorflow as object tf
import tensorflow as tf 
#Importing neural netwoek library - keras
from tensorflow import keras
#importing types of layes for the model
from tensorflow.keras.layers import Input,Dropout,Dense
from tensorflow.keras.models import Model
from tensorflow.keras import regularizers
%matplotlib inline

# READ DATASET

In [3]:
df = pd.read_csv('/content/drive/MyDrive/ISM PROJECT/NSL KDD/KDDTrain+aggregate.csv')
#df_train.drop('20', axis='columns', inplace=True)
df #Training dataframe

duration  protocol_type   service  flag   src_bytes   dst_bytes  \
0              0            tcp  ftp_data    SF         491           0   
1              0            udp     other    SF         146           0   
2              0            tcp   private    S0           0           0   
3              0            tcp      http    SF         232        8153   
4              0            tcp      http    SF         199         420   
...          ...            ...       ...   ...         ...         ...   
125968         0            tcp   private    S0           0           0   
125969         8            udp   private    SF         105         145   
125970         0            tcp      smtp    SF        2231         384   
125971         0            tcp    klogin    S0           0           0   
125972         0            tcp  ftp_data    SF         151           0   

         land   wrong_fragment   urgent   hot  ...   dst_host_srv_count  \
0           0                0        0     0  ...                   25   
1           0                0        0     0  ...                    1   
2           0                0        0     0  ...                   26   
3           0                0        0     0  ...                  255   
4           0                0        0     0  ...                  255   
...       ...              ...      ...   ...  ...                  ...   
125968      0                0        0     0  ...                   25   
125969      0                0        0     0  ...                  244   
125970      0                0        0     0  ...                   30   
125971      0                0        0     0  ...                    8   
125972      0                0        0     0  ...                   77   

         dst_host_same_srv_rate   dst_host_diff_srv_rate  \
0                          0.17                     0.03   
1                          0.00                     0.60   
2                          0.10                     0.05   
3                          1.00                     0.00   
4                          1.00                     0.00   
...                         ...                      ...   
125968                     0.10                     0.06   
125969                     0.96                     0.01   
125970                     0.12                     0.06   
125971                     0.03                     0.05   
125972                     0.30                     0.03   

         dst_host_same_src_port_rate   dst_host_srv_diff_host_rate  \
0                               0.17                          0.00   
1                               0.88                          0.00   
2                               0.00                          0.00   
3                               0.03                          0.04   
4                               0.00                          0.00   
...                              ...                           ...   
125968                          0.00                          0.00   
125969                          0.01                          0.00   
125970                          0.00                          0.00   
125971                          0.00                          0.00   
125972                          0.30                          0.00   

         dst_host_serror_rate    dst_host_srv_serror_rate  \
0                        0.00                        0.00   
1                        0.00                        0.00   
2                        1.00                        1.00   
3                        0.03                        0.01   
4                        0.00                        0.00   
...                       ...                         ...   
125968                   1.00                        1.00   
125969                   0.00                        0.00   
125970                   0.72                        0.00   
125971                   1.00     

In [4]:
X = df.iloc[:, 0:41]
Y = df[' classification.']

In [5]:
X.columns = ['duration',	'protocol_type',	'service',	'flag',	'src_bytes',	'dst_bytes',	'land',	'wrong_fragment',	'urgent',	'hot',	'num_failed_logins',	
                    'logged_in',	'num_compromised',	'root_shell',	'su_attempted',	'num_root',	'num_file_creations',	'num_shells',	'num_access_files',	'num_outbound_cmds',	
                    'is_host_login',	'is_guest_login',	'count',	'srv_count',	'serror_rate',	'srv_serror_rate',	'rerror_rate',	'srv_rerror_rate',	'same_srv_rate',	
                    'diff_srv_rate',	'srv_diff_host_rate',	'dst_host_count',	'dst_host_srv_count',	'dst_host_same_srv_rate',	'dst_host_diff_srv_rate',	'dst_host_same_src_port_rate',	
                    'dst_host_srv_diff_host_rate',	'dst_host_serror_rate',	'dst_host_srv_serror_rate',	'dst_host_rerror_rate',	'dst_host_srv_rerror_rate']
X

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0              0           tcp  ftp_data   SF        491          0     0   
1              0           udp     other   SF        146          0     0   
2              0           tcp   private   S0          0          0     0   
3              0           tcp      http   SF        232       8153     0   
4              0           tcp      http   SF        199        420     0   
...          ...           ...       ...  ...        ...        ...   ...   
125968         0           tcp   private   S0          0          0     0   
125969         8           udp   private   SF        105        145     0   
125970         0           tcp      smtp   SF       2231        384     0   
125971         0           tcp    klogin   S0          0          0     0   
125972         0           tcp  ftp_data   SF        151          0     0   

        wrong_fragment  urgent  hot  ...  dst_host_count  dst_host_srv_count  \
0                    0       0    0  ...             150                  25   
1                    0       0    0  ...             255                   1   
2                    0       0    0  ...             255                  26   
3                    0       0    0  ...              30                 255   
4                    0       0    0  ...             255                 255   
...                ...     ...  ...  ...             ...                 ...   
125968               0       0    0  ...             255                  25   
125969               0       0    0  ...             255                 244   
125970               0       0    0  ...             255                  30   
125971               0       0    0  ...             255                   8   
125972               0       0    0  ...             255                  77   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                         0.17                    0.03   
1                         0.00                    0.60   
2                         0.10                    0.05   
3                         1.00                    0.00   
4                         1.00                    0.00   
...                        ...                     ...   
125968                    0.10                    0.06   
125969                    0.96                    0.01   
125970                    0.12                    0.06   
125971                    0.03                    0.05   
125972                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.17                         0.00   
1                              0.88                         0.00   
2                              0.00                         0.00   
3                              0.03                         0.04   
4                              0.00                         0.00   
...                             ...                          ...   
125968                         0.00                         0.00   
125969                         0.01                         0.00   
125970                         0.00                         0.00   
125971                         0.00                         0.00   
125972                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.05   
1                       0.00                      0.00                  0.00   
2                       1.00                      1.00                  0.00   
3                       0.03                      0.01                  0.00   
4                       0.00                      0.00                  0.00   
...                      ...                       ...                   ...   
125968                  1.00                    

# One HOT ENCODING

In [6]:
#for training data
#defining alias for the converted catagorical features
temp1 = pd.get_dummies(X.protocol_type, prefix='protocol_type')
temp2 = pd.get_dummies(X.service, prefix='service')
temp3 = pd.get_dummies(X.flag, prefix='flag')
#Removing the catagroiacal features from dataframe
X.drop(['protocol_type', 'flag', 'service'], axis='columns', inplace=True)

In [7]:
#Inserting the alias of converted catagorical features to the dataframe
i=1
for col in temp1:
  X.insert(i, col, temp1[col])
  i = i+1
for col in temp2:
  X.insert(i, col, temp2[col])
  i = i+1
for col in temp3:
  X.insert(i, col, temp3[col])
  i = i+1
X

duration  protocol_type_icmp  protocol_type_tcp  protocol_type_udp  \
0              0                   0                  1                  0   
1              0                   0                  0                  1   
2              0                   0                  1                  0   
3              0                   0                  1                  0   
4              0                   0                  1                  0   
...          ...                 ...                ...                ...   
125968         0                   0                  1                  0   
125969         8                   0                  0                  1   
125970         0                   0                  1                  0   
125971         0                   0                  1                  0   
125972         0                   0                  1                  0   

        service_IRC  service_X11  service_Z39_50  service_aol  service_auth  \
0                 0            0               0            0             0   
1                 0            0               0            0             0   
2                 0            0               0            0             0   
3                 0            0               0            0             0   
4                 0            0               0            0             0   
...             ...          ...             ...          ...           ...   
125968            0            0               0            0             0   
125969            0            0               0            0             0   
125970            0            0               0            0             0   
125971            0            0               0            0             0   
125972            0            0               0            0             0   

        service_bgp  ...  dst_host_count  dst_host_srv_count  \
0                 0  ...             150                  25   
1                 0  ...             255                   1   
2                 0  ...             255                  26   
3                 0  ...              30                 255   
4                 0  ...             255                 255   
...             ...  ...             ...                 ...   
125968            0  ...             255                  25   
125969            0  ...             255                 244   
125970            0  ...             255                  30   
125971            0  ...             255                   8   
125972            0  ...             255                  77   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                         0.17                    0.03   
1                         0.00                    0.60   
2                         0.10                    0.05   
3                         1.00                    0.00   
4                         1.00                    0.00   
...                        ...                     ...   
125968                    0.10                    0.06   
125969                    0.96                    0.01   
125970                    0.12                    0.06   
125971                    0.03                    0.05   
125972                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.17                         0.00   
1                              0.88                         0.00   
2                              0.00                         0.00   
3                              0.03                         0.04   
4                              0.00                         0.00   
...                             ...                          ...   
125968                         0.00                         0.00   
125969                         0.01                         0.00   
125970                         0.00         

# SPLITTING INTO TRAINING AND TESTING

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33)

# DROPPING 6 FEATURES

In [9]:
X_train.drop(['land', 'logged_in', 'root_shell', 'num_outbound_cmds', 'is_host_login', 'is_guest_login'], axis = 'columns', inplace=True)
X_train

duration  protocol_type_icmp  protocol_type_tcp  protocol_type_udp  \
36339          0                   0                  1                  0   
44773          5                   0                  1                  0   
36465          0                   0                  1                  0   
45562          0                   0                  1                  0   
23356          0                   0                  1                  0   
...          ...                 ...                ...                ...   
73605          1                   0                  1                  0   
107820         0                   0                  1                  0   
88349          2                   0                  1                  0   
39930          0                   0                  1                  0   
9196           0                   0                  1                  0   

        service_IRC  service_X11  service_Z39_50  service_aol  service_auth  \
36339             0            0               0            0             0   
44773             0            0               0            0             0   
36465             0            0               0            0             0   
45562             0            0               0            0             0   
23356             0            0               0            0             0   
...             ...          ...             ...          ...           ...   
73605             0            0               0            0             0   
107820            0            0               0            0             0   
88349             0            0               0            0             0   
39930             0            0               0            0             0   
9196              0            0               0            0             0   

        service_bgp  ...  dst_host_count  dst_host_srv_count  \
36339             0  ...             255                   2   
44773             0  ...              25                 198   
36465             0  ...             255                   5   
45562             0  ...               5                  24   
23356             0  ...             255                  11   
...             ...  ...             ...                 ...   
73605             0  ...              62                 181   
107820            0  ...             121                 255   
88349             0  ...             106                 184   
39930             0  ...             255                  68   
9196              0  ...             245                 152   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
36339                     0.01                    0.08   
44773                     0.88                    0.08   
36465                     0.02                    0.07   
45562                     1.00                    0.00   
23356                     0.04                    0.07   
...                        ...                     ...   
73605                     0.50                    0.08   
107820                    1.00                    0.00   
88349                     0.72                    0.06   
39930                     0.27                    0.02   
9196                      0.62                    0.09   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
36339                          0.00                         0.00   
44773                          0.04                         0.01   
36465                          0.00                         0.00   
45562                          1.00                         0.12   
23356                          0.00                         0.00   
...                             ...                          ...   
73605                          0.02                         0.01   
107820                         0.01                         0.13   
88349                          0.01         

In [10]:
X_test.drop(['land', 'logged_in', 'root_shell', 'num_outbound_cmds', 'is_host_login', 'is_guest_login'], axis = 'columns', inplace=True)
X_test

duration  protocol_type_icmp  protocol_type_tcp  protocol_type_udp  \
87211          0                   0                  1                  0   
121839         0                   0                  1                  0   
43049          0                   0                  1                  0   
91226          0                   0                  1                  0   
80386          0                   0                  1                  0   
...          ...                 ...                ...                ...   
99959          0                   0                  0                  1   
43497          0                   0                  1                  0   
38853          0                   1                  0                  0   
99402          0                   0                  1                  0   
58777          0                   0                  1                  0   

        service_IRC  service_X11  service_Z39_50  service_aol  service_auth  \
87211             0            0               0            0             0   
121839            0            0               0            0             0   
43049             0            0               0            0             0   
91226             0            0               0            0             0   
80386             0            0               0            0             0   
...             ...          ...             ...          ...           ...   
99959             0            0               0            0             0   
43497             0            0               0            0             0   
38853             0            0               0            0             0   
99402             0            0               0            0             0   
58777             0            0               0            0             0   

        service_bgp  ...  dst_host_count  dst_host_srv_count  \
87211             0  ...             255                 255   
121839            0  ...             255                   4   
43049             0  ...              46                   2   
91226             0  ...             255                   2   
80386             0  ...             201                 255   
...             ...  ...             ...                 ...   
99959             0  ...             255                 248   
43497             0  ...             255                 255   
38853             0  ...             163                   1   
99402             0  ...              71                 255   
58777             0  ...             255                  21   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
87211                     1.00                    0.00   
121839                    0.02                    0.09   
43049                     0.04                    0.11   
91226                     0.01                    0.08   
80386                     1.00                    0.00   
...                        ...                     ...   
99959                     0.97                    0.01   
43497                     1.00                    0.00   
38853                     0.01                    0.03   
99402                     1.00                    0.00   
58777                     0.08                    0.05   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
87211                          0.00                         0.00   
121839                         0.00                         0.00   
43049                          0.02                         0.00   
91226                          0.00                         0.00   
80386                          0.00                         0.01   
...                             ...                          ...   
99959                          0.00                         0.00   
43497                          0.00                         0.00   
38853                          0.01         

# NORMALIZATION

In [11]:
#Using Min-Max Feature : series = (series-min(series))/(max(series)-min(series))
for col in X_train.columns:
  if col != 'protocol_type' and col != 'service' and col != 'flag':
    X_train[col] = (X_train[col] - X_train[col].min())/(X_train[col].max() - X_train[col].min())
X_train

duration  protocol_type_icmp  protocol_type_tcp  protocol_type_udp  \
36339   0.000000                 0.0                1.0                0.0   
44773   0.000117                 0.0                1.0                0.0   
36465   0.000000                 0.0                1.0                0.0   
45562   0.000000                 0.0                1.0                0.0   
23356   0.000000                 0.0                1.0                0.0   
...          ...                 ...                ...                ...   
73605   0.000023                 0.0                1.0                0.0   
107820  0.000000                 0.0                1.0                0.0   
88349   0.000047                 0.0                1.0                0.0   
39930   0.000000                 0.0                1.0                0.0   
9196    0.000000                 0.0                1.0                0.0   

        service_IRC  service_X11  service_Z39_50  service_aol  service_auth  \
36339           0.0          0.0             0.0          0.0           0.0   
44773           0.0          0.0             0.0          0.0           0.0   
36465           0.0          0.0             0.0          0.0           0.0   
45562           0.0          0.0             0.0          0.0           0.0   
23356           0.0          0.0             0.0          0.0           0.0   
...             ...          ...             ...          ...           ...   
73605           0.0          0.0             0.0          0.0           0.0   
107820          0.0          0.0             0.0          0.0           0.0   
88349           0.0          0.0             0.0          0.0           0.0   
39930           0.0          0.0             0.0          0.0           0.0   
9196            0.0          0.0             0.0          0.0           0.0   

        service_bgp  ...  dst_host_count  dst_host_srv_count  \
36339           0.0  ...        1.000000            0.007843   
44773           0.0  ...        0.098039            0.776471   
36465           0.0  ...        1.000000            0.019608   
45562           0.0  ...        0.019608            0.094118   
23356           0.0  ...        1.000000            0.043137   
...             ...  ...             ...                 ...   
73605           0.0  ...        0.243137            0.709804   
107820          0.0  ...        0.474510            1.000000   
88349           0.0  ...        0.415686            0.721569   
39930           0.0  ...        1.000000            0.266667   
9196            0.0  ...        0.960784            0.596078   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
36339                     0.01                    0.08   
44773                     0.88                    0.08   
36465                     0.02                    0.07   
45562                     1.00                    0.00   
23356                     0.04                    0.07   
...                        ...                     ...   
73605                     0.50                    0.08   
107820                    1.00                    0.00   
88349                     0.72                    0.06   
39930                     0.27                    0.02   
9196                      0.62                    0.09   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
36339                          0.00                         0.00   
44773                          0.04                         0.01   
36465                          0.00                         0.00   
45562                          1.00                         0.12   
23356                          0.00                         0.00   
...                             ...                          ...   
73605                          0.02                         0.01   
107820                         0.01                         0.13   
88349                          0.01         

In [12]:
#Using Min-Max Feature : series = (series-min(series))/(max(series)-min(series))
for col in X_test.columns:
  if col != 'protocol_type' and col != 'service' and col != 'flag':
    X_test[col] = (X_test[col] - X_test[col].min())/(X_test[col].max() - X_test[col].min())
X_test

duration  protocol_type_icmp  protocol_type_tcp  protocol_type_udp  \
87211        0.0                 0.0                1.0                0.0   
121839       0.0                 0.0                1.0                0.0   
43049        0.0                 0.0                1.0                0.0   
91226        0.0                 0.0                1.0                0.0   
80386        0.0                 0.0                1.0                0.0   
...          ...                 ...                ...                ...   
99959        0.0                 0.0                0.0                1.0   
43497        0.0                 0.0                1.0                0.0   
38853        0.0                 1.0                0.0                0.0   
99402        0.0                 0.0                1.0                0.0   
58777        0.0                 0.0                1.0                0.0   

        service_IRC  service_X11  service_Z39_50  service_aol  service_auth  \
87211           0.0          0.0             0.0          NaN           0.0   
121839          0.0          0.0             0.0          NaN           0.0   
43049           0.0          0.0             0.0          NaN           0.0   
91226           0.0          0.0             0.0          NaN           0.0   
80386           0.0          0.0             0.0          NaN           0.0   
...             ...          ...             ...          ...           ...   
99959           0.0          0.0             0.0          NaN           0.0   
43497           0.0          0.0             0.0          NaN           0.0   
38853           0.0          0.0             0.0          NaN           0.0   
99402           0.0          0.0             0.0          NaN           0.0   
58777           0.0          0.0             0.0          NaN           0.0   

        service_bgp  ...  dst_host_count  dst_host_srv_count  \
87211           0.0  ...        1.000000            1.000000   
121839          0.0  ...        1.000000            0.015686   
43049           0.0  ...        0.180392            0.007843   
91226           0.0  ...        1.000000            0.007843   
80386           0.0  ...        0.788235            1.000000   
...             ...  ...             ...                 ...   
99959           0.0  ...        1.000000            0.972549   
43497           0.0  ...        1.000000            1.000000   
38853           0.0  ...        0.639216            0.003922   
99402           0.0  ...        0.278431            1.000000   
58777           0.0  ...        1.000000            0.082353   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
87211                     1.00                    0.00   
121839                    0.02                    0.09   
43049                     0.04                    0.11   
91226                     0.01                    0.08   
80386                     1.00                    0.00   
...                        ...                     ...   
99959                     0.97                    0.01   
43497                     1.00                    0.00   
38853                     0.01                    0.03   
99402                     1.00                    0.00   
58777                     0.08                    0.05   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
87211                          0.00                         0.00   
121839                         0.00                         0.00   
43049                          0.02                         0.00   
91226                          0.00                         0.00   
80386                          0.00                         0.01   
...                             ...                          ...   
99959                          0.00                         0.00   
43497                          0.00                         0.00   
38853                          0.01         

In [43]:
X_train.columns

Index(['duration', 'protocol_type_icmp', 'protocol_type_tcp',
       'protocol_type_udp', 'service_IRC', 'service_X11', 'service_Z39_50',
       'service_aol', 'service_auth', 'service_bgp',
       ...
       'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate'],
      dtype='object', length=116)

# Changing Labels

In [13]:
Y_train.unique()

array(['Dos', 'normal', 'R2L', 'Probe', 'U2R'], dtype=object)

In [14]:
# Our new labels
classes = {"normal": 0, "Dos": 1, "R2L": 2, "U2R" : 3, "Probe": 4}
#Funtion to allot the new label for a record passed as attribute
def label_attack (l):
  return classes[l]

In [15]:
#For trainging data
c=[]
for l in Y_train:
  c.append(label_attack(l))
#Changing labels to new labels = 0,1,2,3,4
Y_train = c

In [16]:
set(Y_train)

{0, 1, 2, 3, 4}

In [17]:
#For trainging data
c=[]
for l in Y_test:
  c.append(label_attack(l))
#Changing labels to new labels = 0,1,2,3,4
Y_test = c

In [18]:
set(Y_test)

{0, 1, 2, 3, 4}

# CVAE MODEL

In [19]:
from tensorflow.keras import layers

#orignal shape of trainginfg data is (125972, 116)
original_dim = 116
# Number of nureons in internal layers
intermediate_dim = 500 
 # Special internal layer dimension for a particular layer of decoder to be comined with the labels associated with the inputs for decoder after sampling
id2 = 495
#Dimension of latent variables (output of encoder) 
latent_dim = 25 
#Dimension of labels passed to decoder 
l_dim = 5 

In [20]:
 #Taking 116 features of training data as input for encoder
inputs = keras.Input(shape=(original_dim,))
#Taking 5 labels as input for decoder
label_inputs = keras.Input(shape=(5,), name='label_5') 


#ENCODER
#First hidden layer with 500 neurons and using relu activation funtion taking input, the 116 features of traing dataset
he1 = layers.Dense(intermediate_dim, activation='relu')(inputs) 
#Second hidden layer with 500 neurons and using relu activation funtion taking the output of first hidden layer as input
he2 = layers.Dense(intermediate_dim, activation='relu')(he1)
# Layer with 25 neurons for the mean taking output from second layer as input 
z_mean = layers.Dense(latent_dim)(he2) 
# Layer with 25 neurons for sigma taking output from second layer as input
z_log_sigma = layers.Dense(latent_dim)(he2) 


#Sampling
from keras import backend as K

#Sampling for latent variables to be passed as input for decoder
def sampling(args):
    z_mean, z_log_sigma = args
    sigma = 0.5*z_log_sigma
    epsilon = K.random_normal(shape=(K.shape(sigma)[0], latent_dim))
    return z_mean + K.exp(sigma) * epsilon

#Special layer lamda to call the defined function sampling
z = layers.Lambda(sampling)([z_mean, z_log_sigma])


#DECODER
#First hidden layer with 495 neurons and using relu activation funtion taking input z
hd1 = layers.Dense(id2, activation='relu')(z)
#Second hidden layer with 500 neurons and using relu activation funtion taking the output of first hidden layer concatenated with the 5 unique labels as input
hd2 = layers.Dense(intermediate_dim, input_dim=2, activation="relu")(keras.layers.Concatenate(axis=1)([hd1, label_inputs]))
#output layer of decoder taking input as the output of layer hd2 and using a non linear activation funtion - sigmoid activation function
outputs = layers.Dense(original_dim, activation='sigmoid')(hd2)


#CVAE Model
cvae = keras.Model([inputs, label_inputs], outputs, name='ae_mlp')


#Loss Calculation
reconstruction_loss = keras.losses.binary_crossentropy(inputs, outputs)
reconstruction_loss *= original_dim
kl_loss = 1 + z_log_sigma - K.square(z_mean) - K.exp(z_log_sigma)
kl_loss = K.sum(kl_loss, axis=-1)
kl_loss *= -0.5
#Normalised total caluculated loss of the model
cvae_loss = K.mean(reconstruction_loss + kl_loss)
cvae.add_loss(cvae_loss)


#Compiling the formed cvae model using the adam optimizer
cvae.compile(optimizer='adam')

In [21]:
#Sum up of the whole cvae model formed
cvae.summary()

Model: "ae_mlp"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 116)]        0           []                               
                                                                                                  
 dense (Dense)                  (None, 500)          58500       ['input_1[0][0]']                
                                                                                                  
 dense_1 (Dense)                (None, 500)          250500      ['dense[0][0]']                  
                                                                                                  
 dense_2 (Dense)                (None, 25)           12525       ['dense_1[0][0]']                
                                                                                             

# Fitting Model onto Training Data

In [22]:
label = pd.get_dummies(Y_train, prefix="label")
#Forming tensor of the unique labels
l_tensor = tf.convert_to_tensor(label, dtype=tf.float32)
l_tensor

<tf.Tensor: shape=(84401, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)>

In [23]:
#Forming tensor of the training data features to passed as input
x_tensor = tf.convert_to_tensor(X_train, dtype=tf.float32)
x_tensor 

<tf.Tensor: shape=(84401, 116), dtype=float32, numpy=
array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.1658273e-04, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [4.6633089e-05, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)>

In [24]:
#Fitting the formed CVAE model over the traing dataset
history = cvae.fit([x_tensor, l_tensor], x_tensor, batch_size = 256, epochs = 100, shuffle = True, validation_split = 0.30);

Epoch 1/100
231/231 [==============================] - 9s 36ms/step - loss: 13.0617 - val_loss: 9.0957
Epoch 2/100
231/231 [==============================] - 8s 34ms/step - loss: 8.4115 - val_loss: 7.9757
Epoch 3/100
231/231 [==============================] - 8s 34ms/step - loss: 7.5967 - val_loss: 7.4335
Epoch 4/100
231/231 [==============================] - 8s 35ms/step - loss: 7.2388 - val_loss: 7.1479
Epoch 5/100
231/231 [==============================] - 8s 34ms/step - loss: 7.0191 - val_loss: 7.0252
Epoch 6/100
231/231 [==============================] - 8s 34ms/step - loss: 6.8545 - val_loss: 6.8395
Epoch 7/100
231/231 [==============================] - 8s 35ms/step - loss: 6.7481 - val_loss: 6.7409
Epoch 8/100
231/231 [==============================] - 8s 36ms/step - loss: 6.6507 - val_loss: 6.6899
Epoch 9/100
231/231 [==============================] - 8s 35ms/step - loss: 6.5645 - val_loss: 6.6293
Epoch 10/100
231/231 [==============================] - 8s 35ms/step - loss: 6.51

In [25]:
#Testing the fitted model with training data
pred_train = cvae.predict([x_tensor, l_tensor])
pred_train

array([[7.5681805e-07, 6.1506262e-06, 9.9999958e-01, ..., 9.9991310e-01,
        2.1824701e-06, 2.6793302e-08],
       [5.3155960e-05, 4.3916629e-07, 9.9999011e-01, ..., 2.1496713e-03,
        5.2171946e-03, 4.1507185e-03],
       [6.7747801e-06, 1.1376870e-16, 1.0000000e+00, ..., 9.9979109e-01,
        3.7381199e-07, 1.0677829e-07],
       ...,
       [3.4569224e-05, 7.3214026e-13, 1.0000000e+00, ..., 1.1165917e-02,
        1.1950791e-02, 2.3038387e-03],
       [7.2003652e-09, 2.1188733e-16, 1.0000000e+00, ..., 9.9768698e-01,
        9.7789143e-06, 1.4585595e-07],
       [1.2668967e-04, 2.1774263e-10, 1.0000000e+00, ..., 9.2568398e-03,
        1.5718341e-02, 9.8049641e-04]], dtype=float32)

# Evaluation on Test Data

In [26]:
#5 unique labels of testing data
l_test = pd.get_dummies(Y_test, prefix='label')
l_t =  tf.convert_to_tensor(l_test)
l_t

<tf.Tensor: shape=(41572, 5), dtype=uint8, numpy=
array([[0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       ...,
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=uint8)>

In [27]:
X_test_tensor = tf.convert_to_tensor(X_test)
X_test_tensor

<tf.Tensor: shape=(41572, 116), dtype=float64, numpy=
array([[0.  , 0.  , 1.  , ..., 0.01, 0.04, 0.04],
       [0.  , 0.  , 1.  , ..., 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , ..., 1.  , 0.  , 0.  ],
       ...,
       [0.  , 1.  , 0.  , ..., 0.  , 0.01, 0.  ],
       [0.  , 0.  , 1.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , ..., 1.  , 0.  , 0.  ]])>

# Prediciton with different labels

[1,0,0,0,0]

In [28]:
label_t = [[1,1,1,1,1]]*41572
label_t = pd.DataFrame(label_t)
label_t = tf.convert_to_tensor(label_t)
label_t

<tf.Tensor: shape=(41572, 5), dtype=int64, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       ...,
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [29]:
pred1 = cvae.predict([X_test_tensor, label_t])
pred1

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

[0,1,0,0,0]

In [30]:
label_t = [[0,1,0,0,0]]*41572
label_t = tf.convert_to_tensor(label_t)
label_t

<tf.Tensor: shape=(41572, 5), dtype=int32, numpy=
array([[0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=int32)>

In [31]:
pred2 = cvae.predict([X_test_tensor, label_t])
pred2

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

[0,0,1,0,0]

In [32]:
label_t = [[0,0,1,0,0]]*41572
label_t = tf.convert_to_tensor(label_t)
label_t

<tf.Tensor: shape=(41572, 5), dtype=int32, numpy=
array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int32)>

In [33]:
pred3 = cvae.predict([X_test_tensor, label_t])
pred3

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

[0,0,0,1,0]

In [34]:
label_t = [[0,0,0,1,0]]*41572
label_t = tf.convert_to_tensor(label_t)
label_t

<tf.Tensor: shape=(41572, 5), dtype=int32, numpy=
array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]], dtype=int32)>

In [35]:
pred4 = cvae.predict([X_test_tensor, label_t])
pred4

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

[0,0,0,0,1]

In [36]:
label_t = [[0,0,0,0,1]]*41572
label_t = tf.convert_to_tensor(label_t)
label_t

<tf.Tensor: shape=(41572, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       ...,
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]], dtype=int32)>

In [37]:
pred5 = cvae.predict([X_test_tensor, label_t])
pred5

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

# Label Selection

In [38]:
X_tn = X_test.to_numpy()
X_tn

array([[0.  , 0.  , 1.  , ..., 0.01, 0.04, 0.04],
       [0.  , 0.  , 1.  , ..., 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , ..., 1.  , 0.  , 0.  ],
       ...,
       [0.  , 1.  , 0.  , ..., 0.  , 0.01, 0.  ],
       [0.  , 0.  , 1.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , ..., 1.  , 0.  , 0.  ]])

In [39]:
import numpy as np

lr = []

for i in range(41572):
  d = []
  d.append(np.linalg.norm(pred1[i] - X_tn[i]))
  d.append(np.linalg.norm(pred2[i] - X_tn[i]))
  d.append(np.linalg.norm(pred3[i] - X_tn[i]))
  d.append(np.linalg.norm(pred4[i] - X_tn[i]))
  d.append(np.linalg.norm(pred5[i] - X_tn[i]))

  lr.append(d.index(min(d)))


In [40]:
from sklearn import metrics

metrics.multilabel_confusion_matrix(Y_test, Y_test)

array([[[19175,     0],
        [    0, 22397]],

       [[26500,     0],
        [    0, 15072]],

       [[41261,     0],
        [    0,   311]],

       [[41557,     0],
        [    0,    15]],

       [[37795,     0],
        [    0,  3777]]])

# Regenerated Data

In [44]:
re = pd.DataFrame(pred_train)
re

0             1         2             3             4    \
0      7.568181e-07  6.150626e-06  1.000000  1.739125e-13  4.988345e-17   
1      5.315596e-05  4.391663e-07  0.999990  4.836936e-06  3.281295e-11   
2      6.774780e-06  1.137687e-16  1.000000  2.870844e-25  2.515693e-26   
3      1.314026e-02  8.021282e-07  0.999974  1.181875e-09  4.990096e-17   
4      3.277996e-05  6.483295e-14  1.000000  3.386023e-11  1.388111e-08   
...             ...           ...       ...           ...           ...   
84396  8.080995e-09  1.203070e-12  1.000000  1.895635e-13  1.252225e-16   
84397  3.602316e-06  5.241560e-13  0.999999  1.402177e-08  7.092887e-20   
84398  3.456922e-05  7.321403e-13  1.000000  1.981186e-10  4.371057e-10   
84399  7.200365e-09  2.118873e-16  1.000000  1.452712e-15  5.197350e-20   
84400  1.266897e-04  2.177426e-10  1.000000  2.119186e-07  1.049571e-06   

                5             6             7             8             9    \
0      1.025851e-19  6.038411e-05  5.677152e-16  1.705938e-07  1.143244e-10   
1      1.340077e-10  8.824133e-11  4.674300e-16  2.657981e-09  1.828026e-08   
2      1.477215e-32  2.378640e-09  8.249192e-22  3.753054e-13  1.435279e-21   
3      2.035945e-16  4.450682e-15  1.782505e-20  4.212841e-11  1.666107e-16   
4      2.751231e-08  4.781530e-07  1.309051e-11  3.434122e-04  8.938313e-04   
...             ...           ...           ...           ...           ...   
84396  3.661416e-18  3.415994e-10  1.158340e-22  4.617082e-10  1.041016e-06   
84397  3.837528e-17  1.989739e-11  2.221601e-17  7.704205e-13  2.162041e-09   
84398  3.697811e-08  2.628294e-12  1.883672e-18  9.408644e-07  1.783494e-09   
84399  2.916342e-18  3.571487e-05  9.250688e-21  1.058646e-01  9.958109e-08   
84400  7.997268e-05  1.200689e-12  1.458565e-15  1.740594e-07  6.087186e-09   

       ...       106       107       108       109       110           111  \
0      ...  0.981202  0.038962  0.040325  0.057058  0.000382  7.704780e-05   
1      ...  0.369587  0.778943  0.880231  0.019952  0.103513  2.298626e-02   
2      ...  0.999944  0.051187  0.030568  0.054305  0.000296  8.402256e-07   
3      ...  0.016754  0.165245  0.996692  0.001397  0.998021  1.636127e-01   
4      ...  0.998618  0.031702  0.024224  0.064734  0.000133  4.332521e-05   
...    ...       ...       ...       ...       ...       ...           ...   
84396  ...  0.579413  0.722989  0.680785  0.051667  0.031112  1.545757e-02   
84397  ...  0.270975  0.974801  0.999068  0.000260  0.106245  3.462631e-02   
84398  ...  0.648555  0.483488  0.475401  0.083442  0.028288  2.727842e-02   
84399  ...  0.994956  0.086112  0.066862  0.068611  0.000245  4.791915e-04   
84400  ...  0.615437  0.573697  0.614597  0.066141  0.021084  7.378668e-03   

            112       113           114           115  
0      0.998452  0.999913  2.182470e-06  2.679330e-08  
1      0.009586  0.002150  5.217195e-03  4.150718e-03  
2      0.999664  0.999791  3.738120e-07  1.067783e-07  
3      0.005868  0.001860  1.459122e-04  4.895031e-04  
4      0.000011  0.000019  9.999768e-01  9.999938e-01  
...         ...       ...           ...           ...  
84396  0.003762  0.001510  6.086230e-04  4.059970e-04  
84397  0.001841  0.000485  5.836403e-02  1.012752e-01  
84398  0.035750  0.011166  1.195079e-02  2.303839e-03  
84399  0.999381  0.997687  9.778914e-06  1.458559e-07  
84400  0.059193  0.009257  1.571834e-02  9.804964e-04  

[84401 rows x 116 columns]